# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Portfolio',
                'doc_host': 'https://robitsar.github.io',
                'git_url': 'https://github.com/robitsar/Portfolio',
                'lib_path': 'Portfolio'},
  'syms': {'Portfolio.core': {'Portfolio.core.foo': ('core.html#foo', 'Portfolio/core.py')}}}
